export const GET_QUESTIONS_LIST_SUCCESS = "GET_QUESTIONS_LIST_SUCCESS"
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS"

export const START_QUESTION_EDIT = "START_QUESTION_EDIT"
export const CANCEL_QUESTION_EDIT = "CANCEL_QUESTION_EDIT"
export const PUT_QUESTION_EDIT = "PUT_QUESTION_EDIT"
export const SUCCESS_QUESTION_EDIT = "SUCCESS_QUESTION_EDIT"
